code/bloccit/config/routes.rb
Rails.application.routes.draw do
  resources :topics do
    resources :posts, except: [:index]
  end

  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]

    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end

  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]

  get 'about' => 'welcome#about'
  root 'welcome#index'
end

code/bloccit/app/models/vote.rb
class Vote < ActiveRecord::Base
    belongs_to :user
    belongs_to :post
    after_save :update_post
    
    validates :value, inclusion: { in: [-1, 1], message: "%{value} is not a valid vote." }, presence: true

    private

    def update_post
     post.update_rank
    end
end

code/bloccit/app/controllers/votes_controller.rb
class VotesController < ApplicationController
   before_action :require_sign_in
 
   def up_vote
     update_vote(1)
     redirect_to :back
   end
    
   def down_vote
     update_vote(-1)
     redirect_to :back
   end
    
   private  
   def update_vote(new_value)
     @post = Post.find(params[:post_id])
     @vote = @post.votes.where(user_id: current_user.id).first
 
     if @vote
       @vote.update_attribute(:value, new_value)
     else
       @vote = current_user.votes.create(value: new_value, post: @post)
     end
   end
end

code/bloccit/app/helpers/votes_helper.rb
module VotesHelper
end

code/bloccit/app/views/votes/_voting.html.erb
<% if current_user %> 
    <div class="vote-arrows pull-left">
       <div><%= link_to " ", post_up_vote_path(post), class: 'glyphicon glyphicon-chevron-up', method: :post %></div>
       <div><strong><%= post.points %></strong></div>
       <div><%= link_to " ", post_down_vote_path(post), class: 'glyphicon glyphicon-chevron-down', method: :post %></div>
     </div>
 <% end %>